### PR TITLE
Rename MKL.jl to IntelMKL.jl

### PR DESCRIPTION
**Pull request by DilumAluthge**
This PR renames MKL.jl to IntelMKL.jl.

Of course, after this PR is merged, you will need to rename the GitHub repository as well.

cc: @andreasnoack

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@Kristofferc do you feel strongly about keeping the name the way it is? You can reopen and merge https://github.com/JuliaRegistries/General/pull/6953 if you want.

**Comment by KristofferC** [comment]
I thought it was already registered and didn't think it was a big enough deal to change the name.

**Comment by DilumAluthge** [comment]
Ah. Yeah it's not registered yet.

**Comment by DilumAluthge** [comment]
Bump @andreasnoack

**Comment by DilumAluthge** [comment]
I'm going to close this as stale.

**Pull request closed without merging**
